# Generated by Django 3.1.4 on 2020-12-18 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiquette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True, verbose_name='Code')),
                ('created', models.DateTimeField(db_index=True, editable=False, verbose_name='Date de Création')),
            ],
        ),
        migrations.CreateModel(
            name='FamilleArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(db_index=True, max_length=50, verbose_name='Libelle')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(db_index=True, max_length=50, verbose_name='Nom')),
                ('created', models.DateTimeField(db_index=True, editable=False, verbose_name='Date de Création')),
                ('etiquette', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.etiquette')),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.famillearticle')),
            ],
        ),
    ]
