# Generated by Django 3.1.4 on 2020-12-30 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krabophile', '0001_initial'),
        ('location', '0002_auto_20201218_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='prix_facture_si_non_rendu',
            field=models.FloatField(default=0, verbose_name='Prix si non rendu'),
        ),
        migrations.AddField(
            model_name='famillearticle',
            name='duree_pret',
            field=models.IntegerField(db_index=True, null=True, verbose_name='Duree pret / loca (j)'),
        ),
        migrations.CreateModel(
            name='Pret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_location', models.FloatField(blank=True, db_index=True, default=0, verbose_name='Prix')),
                ('date_restitution', models.DateTimeField(db_index=True, verbose_name='A rendre avant le')),
                ('created', models.DateTimeField(db_index=True, editable=False, verbose_name='Date de Création')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.article')),
                ('krabophile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krabophile.krabophile')),
            ],
        ),
    ]
