# Generated by Django 3.1.4 on 2021-01-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20201230_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etiquette',
            name='code',
        ),
    ]
