# Generated by Django 3.1.4 on 2021-01-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_remove_etiquette_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='created',
        ),
    ]
