# Generated by Django 3.1.5 on 2021-01-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_remove_article_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['etiquette__id']},
        ),
        migrations.AlterModelOptions(
            name='etiquette',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='famillearticle',
            options={'ordering': ['libelle']},
        ),
        migrations.RemoveField(
            model_name='pret',
            name='created',
        ),
        migrations.AlterField(
            model_name='etiquette',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
