# Generated by Django 3.1.5 on 2021-01-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_auto_20210127_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pret',
            name='date_restitution',
            field=models.DateField(db_index=True, verbose_name='A rendre avant le'),
        ),
    ]
