# Generated by Django 3.1.4 on 2020-12-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Krabophile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(db_index=True, max_length=150, verbose_name='Nom')),
                ('nom', models.CharField(db_index=True, max_length=150, verbose_name='Nom')),
                ('adresse', models.CharField(max_length=250, verbose_name='Adresse')),
                ('adresse_complement', models.CharField(blank=True, default='', max_length=250, verbose_name='Adresse (complément)')),
                ('code_postal', models.CharField(db_index=True, default='', max_length=10, verbose_name='Code Postal')),
                ('ville', models.CharField(db_index=True, max_length=150, verbose_name='Ville')),
                ('societaire', models.BooleanField(db_index=True, default=False, verbose_name='Sociétaire')),
                ('actif', models.BooleanField(db_index=True, default=True, verbose_name='Sociétaire')),
                ('created', models.DateTimeField(db_index=True, editable=False, verbose_name='Date de Création')),
                ('updated', models.DateTimeField(db_index=True, editable=False, verbose_name='Date de Création')),
            ],
        ),
    ]
