# Generated by Django 3.1.5 on 2021-01-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krabophile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='krabophile',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='krabophile',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='krabophile',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
